# The name of the project shown in the navigation bar (it links to the
# home page).
name: "Divvy data exploration project"

# Link to the source repository (e.g., on Github, Gitlab).
repo: "http://github.com/stephenslab/ipynb-website"

# Footer added to the bottom of some webpages.
footer: "&copy; 2017 Peter Carbonetto &amp; Gao Wang"

# When set to True, populate each notebook with the commit id (SHA1)
# and commit modification date. This commit info is added underneath
# the cell containing a top-level header; e.g., # Project title in a
# Markdown cell, and <h1>Project title</h1> in the rendered HTML. If
# there is no <h1> tag then the commit info will not be added to the
# webpage.
add_commit_info: True

# These subdirectories contain Jupyter notebooks that will be rendered
# into webpages.
include_dir: ["analysis", "setup", "license"]

# Do not add links in the navigation bar for the Jupyter notebooks in
# these subdirectories.
hide_navbar: ["analysis"]

# Any Jupyter notebooks listed here will not be rendered into webpages
# (e.g., "analysis/temp.ipynb").
exclude_file: []

# This is the notebook used to generate the home page for the
# website. If no home page is set, an Overview.ipynb file is
# automatically generated and saved in the base project directory.
homepage: "analysis/index.ipynb"

# The name of the homepage link shown in the navigation bar.
homepage_label: "Overview"

# The name of the link to the source repository. It is shown in the
# top-right corner of the navigation bar. If this line is removed or
# commented out, then the default is to show a Github logo (the
# "Octocat").
source_label: "source"

# Bootstrap theme. Current supported themes are "cerulean", "flatly"
# and "readable"; see the docs/css directory.
theme: "readable"

# Font used to show all code and text in the Jupyter notebooks (e.g.,
# "Droid Sans"). Set to NULL to inherit the font used by the Bootsrap
# theme.
font: NULL

# Set to True to add a table-of-contents (TOC) to the left-hand side
# of each of the Jupyter notebook webpages; otherwise, set to False.
notebook_toc: False

# Set this variable to enable auto-commit.
# release_message: "Build website with jnbinder."
