# The name of the project shown in the navigation bar (it links to the
# home page).
name: "PCA demo"

# Link to the source repository (e.g., on Github).
repo: "http://github.com/pcarbo/ipynb-demo"

# The footer is included...
footer: "&copy 2017 Peter Carbonetto"

# These directories contain .ipynb notebooks that will be rendered
# into webpages.
include_dir: ["analysis", "license"]

# Any .ipynb notebooks listed here will not be rendered into webpages
# (e.g., "analysis/temp.Rmd").
exclude_file: []

# Notebook used to generate home page.
homepage: "analysis/index.ipynb"

# The name of the homepage link shown in the navigation bar.
homepage_label: "Overview"

# The name of the link to the source repository. It is shown in the
# top-right corner of the navigation bar. If this line is removed or
# commented out, then the default is to show a Github logo ("Octocat").
source_label: "source"

# Bootstrap theme; see the files in docs/site_libs/bootstrap-3.3.5/css
# for the available themes.
theme: "readable"

# Font used to show all code and text in the .ipynb notebooks (e.g.,
# "Droid Sans"). Set to NULL to inherit the font used by the Bootsrap
# theme.
font: NULL

# Set this variable to enable auto-commit.
# release_message: "Build website with jnbinder."

